version: '3.2'

services:
  camerenerve:
    image: index.docker.io/zaker237/camerenerve:backend
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    volumes:
      - ./database:/app/database
